### PR TITLE
Added debian search paths

### PR DESCRIPTION
**Pull request by battarsa**
Hi, I have added Debian search paths, some files in Debian have different locations.

### CODE REVIEW

**Comment by bluezio** [comment]
Thanks for adding the getopt-based option parsing, but why did you remove the package installation code? Some users may need this bit of functionality.

**Comment by battarsa** [comment]
I'm trying to create a "debian" version of the script.
Removing installation code is a first step, next I will add metadata to create a .deb
If you want I can revert and create separate commits.

**Comment by bluezio** [comment]
Right, I see. The idea of creating a Debianized version is great, but in that case it may be better to perhaps split the script into two:

* Keep a "prepare-videochat.sh" script, which does the installation bits as usual, and then calls "run-videochat.sh" (you can `source` the script).
* "run-videochat.sh" would be the script your Debian package or any "prepared" environment uses (e.g. any other Linux system after running prepare-videochat.sh).

This way we don't lose capabilities or duplicate the code, and your Debian package can just keep the main `run-videochat.sh`.

**Comment by bluezio** [comment]
Sorry, but I won't be able to merge these changes unless we can keep existing non-Debian users happy. There have been several contributions from Arch users, and I'd like to keep the script working from them as is.

I'll close for now due to inactivity - feel free to reopen if you have a version with the proposed split, which does not result in losing functionality for non-Debian users.

**Comment by battarsa** [comment]
Hi, I think I have mess up things with the request.
The work on "debian" part is still work in progress.
My pull request had to be only for the two first commits.

**Pull request closed without merging**
